version: 2.1

# Define the jobs  we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: guillemcordoba/rsm
    steps:
      - checkout
      - run:
          name: build-holochain
          working_directory: ~/project/zome
          command: | 
            CARGO_TARGET_DIR=target cargo build --release --target wasm32-unknown-unknown
            dna-util -c todo_rename_zome.dna.workdir/
      - run:
          name: test-holochain
          working_directory: ~/project/zome/tests
          command: |
            NODE_ENV=development npm install
            npm test
      - run:
          name: build-ui
          working_directory: ~/project/ui
          command: |
            NODE_ENV=development npm install
            npm run lint
            npm run build
      - run:
          name: test-ui
          working_directory: ~/project/ui
          command: |
            npm i -g @holochain-open-dev/holochain-run-dna
            npm test
            npm run e2e

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-and-test
